#!/bin/bash
output="$1";
html2text |
sed "s/’/'/g;s/æ/ae/g;s/[“”]/\"/g;s/[^a-zA-Z0-9\.,'\"]/ /g;" |
tr -d '©' |
text2wave -f 13000 -scale 2 |
ffmpeg -i pipe:0  -filter:a "atempo=1.3" -acodec libgsm_ms -ar 8000 -ab 13000 -ac 1 -f wav "$output" -y;
#ffmpeg -i pipe:0 -codec:a libmp3lame -ac 1 -qscale:a 9 "${epub}.mp3";
