#!/bin/bash
set -eux -o pipefail

# Install
# sudo apt install ffmpeg
# sudo pip install --upgrade youtube_dl
# git clone ???spxfy

url="$1";

sshToSrv() {
  ssh -C -p "$homePort" "$homeServer" "$@";
}

name="$(echo "$url"|sed 's|.*/\([^?]*\)?.*|\1|')";
echo "$name";
downloadNEncode="
  set -x;
  wget '$url' -O - |
  ffmpeg -i pipe:0 -acodec libgsm_ms -ar 8000 -ab 13000 -ac 1 -af "volume=1.5" -f wav -";
  # ffmpeg -i pipe:0 -acodec libspeex -ar 8000 -ab 4000 -vbr 1 -compression_level 10 -dtx 1 -ac 1 -af "volume=1.5" -y -f spx -"
sshToSrv "$downloadNEncode" > "$downloadDir/$name.wav"
