#!/bin/bash
set -eux -o pipefail

# Install
# sudo apt install ffmpeg
# sudo pip install --upgrade youtube_dl
# git clone ???spxfy

url="$1";

sshToSrv() {
  ssh -C -p "$port" "$server" "$@";
}

name="$(sshToSrv "youtube-dl --get-title $url |sed 's/[^a-zA-Z0-9]/-/g;'|cut -c 1-30")";
downloadNEncode="
  youtube-dl --output - --exec 'spxfy {}' $url |
  ffmpeg -i pipe:0 -acodec libspeex -ar 8000 -ab 4000 -vbr 1 -compression_level 10 -dtx 1 -ac 1 -af "volume=1.5" -y -f spx -"
sshToSrv "$downloadNEncode" > "$name.spx"
