#!/bin/bash
set -eux -o pipefail

# Install
# sudo apt install ffmpeg
# sudo pip install --upgrade youtube_dl
# git clone ???spxfy

url="$1";

sshToSrv() {
  ssh -C -p "$homePort" "$homeServer"; # "$@";
}

prepScript() {
  url="$@";
  sed "s|{{url}}|$url|g" <<EOF
  name="$(youtube-dl --get-title '{{url}}' |sed 's/[^a-zA-Z0-9]/-/g;'|cut -c 1-30)";
  cat /dev/null |youtube-dl --output - '{{url}}' |
    ffmpeg -i pipe:0 -acodec libgsm_ms -ar 8000 -ab 13000 -ac 1 -af 'volume=1.5' -f wav \\
    1>\"/home/unpriv/sync/$name.wav\" 2>/dev/null &
  disown %%;
EOF
}

#donwloadNEncode="$(prepScript "$url")";
cat /dev/null |
  prepScript "$url" |
  sshToSrv \
  1> /dev/null 2>/dev/null &

disown %%;

